name: Build Proxy List

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      - name: 下载 Clash Core（稳定版）
        run: |
          wget -O clash.gz https://github.com/MetaCubeX/mihomo/releases/download/v1.19.20/mihomo-linux-amd64-v1-v1.19.20.gz
          gunzip clash.gz
          chmod +x clash
          ./clash -v

      - name: 运行脚本
        run: python main.py

      # ✅ 发布到仓库（生成订阅链接）
      - name: 提交结果
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@example.com"
          git add output/*
          git commit -m "update proxies" || echo "no changes"
          git push
